name: slashit
description: Slashit payment gateway. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^3.0.3
  fluttertoast: ^4.0.1
  graphql_flutter: ^3.1.0
  cupertino_icons: ^0.1.3
  progress_dialog: ^1.2.2
  shared_preferences: ^0.5.3+1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  flutter_paystack: ^1.0.3+1
  url_launcher: ^5.5.0
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  date_time_format: ^1.0.0+4
  barcode_widget: ^1.5.0
  badges : ^1.1.1
  dio: ^3.0.9
  flutter_typeahead: ^1.8.8
  share: ^0.6.2+1
  #Image Picker and Cropper
  image_cropper: ^1.2.2
  image_picker: ^0.6.6+1




dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/slashit.jpeg"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Hearticon
      fonts:
        - asset: fonts/hearticon.ttf
    - family: GalaxyIcon
      fonts:
        - asset: fonts/Galaxy.ttf

    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf

    - family: Poppins
      fonts:
        - asset: fonts/poppinsbold.ttf
        - asset: fonts/poppinsmedium.ttf
        - asset: fonts/poppinsregular.ttf
        - asset: fonts/poppinssemibold.ttf

    - family: SourceSans
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-VariableFont_wght.ttf

    - family: Roboto
      fonts:
        - asset: fonts/roboto.ttf

    - family: Bebas
      fonts:
        - asset: fonts/bebas.ttf
